site_name: Mowglixx's Notebook
repo_url: https://github.com/mowglixx/notes/

theme:
    name: dracula
plugins:
  - search  # Material for MkDocs search plugin
  - pub-blog
  - pub-obsidian
  - pub-social
  - pub-meta
  - pub-minifier