site_name: Mowglixx's Notebook
repo_url: https://github.com/mowglixx/notes/

theme:
    name: material
plugins:
  - search  # Material for MkDocs search plugin
  - pub-blog
  - pub-obsidian:
    obsidian_dir: .obsidian
    templates_dir: _templates
    links:
      wikilinks_enabled: true
      img_lazy: true
  - pub-social
  - pub-meta
  - pub-minifier